[package]
name = 'AptosPadCoinBoot'
version = '1.0.0'
upgrade_policy = "compatible"

[addresses]
aptospad = "e3cd31797b9b36ce3cb9617871fb0fa1187d1381aff01b49d72c87f56e27238e"
aptospad_admin = "e3cd31797b9b36ce3cb9617871fb0fa1187d1381aff01b49d72c87f56e27238e"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/move-stdlib"

[dev-dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-stdlib"