[package]
name = 'AptosPadCoin'
version = '1.0.0'
upgrade_policy = "compatible"

[addresses]
aptospad_coin = "1c07732f8f9bed7ee795519629ce8c334d08348fccadbb473d859464042a3ba7"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/move-stdlib"